// <auto-generated />
using System;
using GuitarManager.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GuitarManager.DataAccess.Migrations
{
    [DbContext(typeof(GuitarManagerStorageContext))]
    [Migration("20210307185126_Account_ColumnNameFix")]
    partial class Account_ColumnNameFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Account")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Account")
                        .IsUnique()
                        .HasFilter("[Account] IS NOT NULL");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.GuitarManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GuitarManufacturerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("GuitarManufacturers");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.GuitarType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("GuitarTypes");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.InstalledString", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MyInstrumentID")
                        .HasColumnType("int");

                    b.Property<int>("SoundID")
                        .HasColumnType("int");

                    b.Property<int>("StringID")
                        .HasColumnType("int");

                    b.Property<int>("StringPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MyInstrumentID");

                    b.HasIndex("SoundID");

                    b.HasIndex("StringID");

                    b.ToTable("InstalledStrings");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Instrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GuitarManufacturerID")
                        .HasColumnType("int");

                    b.Property<int>("GuitarTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NumberOfStrings")
                        .HasColumnType("int");

                    b.Property<int>("ScaleLenghtBass")
                        .HasColumnType("int");

                    b.Property<int>("ScaleLenghtTreble")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuitarManufacturerID");

                    b.HasIndex("GuitarTypeID");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.MyInstrument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HoursWeekly")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastDeepCleaning")
                        .HasColumnType("Date");

                    b.Property<DateTime>("LastStringChange")
                        .HasColumnType("Date");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentID");

                    b.HasIndex("PlayerID");

                    b.ToTable("MyInstruments");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CareStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayStyle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Sound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Frequency")
                        .HasColumnType("float");

                    b.Property<string>("Pitch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sounds");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.String", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("BulkDensity")
                        .HasColumnType("float");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.Property<int>("StringManufacturerID")
                        .HasColumnType("int");

                    b.Property<int>("StringTypeID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StringManufacturerID");

                    b.HasIndex("StringTypeID");

                    b.ToTable("String");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringInSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("StringID")
                        .HasColumnType("int");

                    b.Property<int>("StringPosition")
                        .HasColumnType("int");

                    b.Property<int>("StringSetID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StringID");

                    b.HasIndex("StringSetID");

                    b.ToTable("StringsInSets");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StringManufacturerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("StringManufacturers");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GuitarTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NumberOfStrings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuitarTypeID");

                    b.ToTable("StringSets");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("StringTypes");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Account", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.Player", "PlayerID")
                        .WithOne("AccountID")
                        .HasForeignKey("GuitarManager.DataAccess.Entities.Account", "Account");

                    b.Navigation("PlayerID");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.InstalledString", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.MyInstrument", null)
                        .WithMany("InstalledStrings")
                        .HasForeignKey("MyInstrumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarManager.DataAccess.Entities.Sound", null)
                        .WithMany("InstalledStrings")
                        .HasForeignKey("SoundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarManager.DataAccess.Entities.String", null)
                        .WithMany("InstalledStrings")
                        .HasForeignKey("StringID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Instrument", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.GuitarManufacturer", null)
                        .WithMany("Instruments")
                        .HasForeignKey("GuitarManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarManager.DataAccess.Entities.GuitarType", null)
                        .WithMany("Instruments")
                        .HasForeignKey("GuitarTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.MyInstrument", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.Instrument", null)
                        .WithMany("MyInstruments")
                        .HasForeignKey("InstrumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarManager.DataAccess.Entities.Player", null)
                        .WithMany("MyInstruments")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.String", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.StringManufacturer", null)
                        .WithMany("Strings")
                        .HasForeignKey("StringManufacturerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarManager.DataAccess.Entities.StringType", null)
                        .WithMany("Strings")
                        .HasForeignKey("StringTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringInSet", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.String", null)
                        .WithMany("StringsInSets")
                        .HasForeignKey("StringID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuitarManager.DataAccess.Entities.StringSet", null)
                        .WithMany("StringsInSets")
                        .HasForeignKey("StringSetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringSet", b =>
                {
                    b.HasOne("GuitarManager.DataAccess.Entities.GuitarType", null)
                        .WithMany("StringSets")
                        .HasForeignKey("GuitarTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.GuitarManufacturer", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.GuitarType", b =>
                {
                    b.Navigation("Instruments");

                    b.Navigation("StringSets");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Instrument", b =>
                {
                    b.Navigation("MyInstruments");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.MyInstrument", b =>
                {
                    b.Navigation("InstalledStrings");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Player", b =>
                {
                    b.Navigation("AccountID");

                    b.Navigation("MyInstruments");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.Sound", b =>
                {
                    b.Navigation("InstalledStrings");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.String", b =>
                {
                    b.Navigation("InstalledStrings");

                    b.Navigation("StringsInSets");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringManufacturer", b =>
                {
                    b.Navigation("Strings");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringSet", b =>
                {
                    b.Navigation("StringsInSets");
                });

            modelBuilder.Entity("GuitarManager.DataAccess.Entities.StringType", b =>
                {
                    b.Navigation("Strings");
                });
#pragma warning restore 612, 618
        }
    }
}
